spring:
  application:
    name: project-spring-1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8082

